eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
server:
  port: 8888
  ip: localhost
token:
  client_id: client_1
  type: client_credentials
  scope: select
  client_secret: 123456
  url: http://localhost:8052/oauth/token
spring:
  application:
    name: account
  cloud:
      client:
        ipAddress: localhost
  mail:
    ip: 47.105.127.125
    port: 8888
    protocol: smtp #smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
    host: smtp.deepthoughtdata.com #邮件发送服务器的主机，这里采用的是qq邮箱来发送邮件
    sTime: 1800000 #邮件验证码过期时间
    username: aistudioadmin@deepthoughtdata.com #邮件发送服务器的用户名
    password: Mengxin_83
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL证书Socket工厂
            port: 465 #使用SMTP465端口
          auth: true
          starttls:
            enable: false
            required: false
  #数据库配置mysql
  datasource:
    url: jdbc:mysql://182.92.82.3/ai_studio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
    ####### reids 配置信息#######
  redis:
    host: 47.105.127.125
    database: 0
    port: 6479
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 2000ms
    password: Deepthought2018
#172.16.31.233
#6379
##自定义文件地址配置##
file:
  address: /user/hadoop
##hadoop文件系统参数定义##
hadoop:
  mapProps:
    defaultFs: fs.defaultFS
    host: hdfs://47.105.127.125:9000
    defaultImagePath: /user/hadoop/default/image/001.jpg
####hive配置#####
hive:
  url: jdbc:hive2://47.105.127
  port: 10000
  schema: default
  user: root
  password: 111111
