server:
  port: 8081
  servlet:
    context-path: /stretch
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.81.16:8080/stretch/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    #告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: in
spring:
  cloud:
    client:
      ipAddress: 172.16.81.16
  application:
    name: account