server:
  port: 8888
  ip: localhost
token:
  client_id: client_1
  type: client_credentials
  scope: select
  client_secret: 123456
  url: http://localhost:8082/oauth/token
spring:
  mail:
    protocol: smtp #smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
    host: smtp.qq.com #邮件发送服务器的主机，这里采用的是qq邮箱来发送邮件
    port: 25  #邮件发送服务器的端口
    username: 1046276907@qq.com #邮件发送服务器的用户名
    password: efivwhcchnoobbee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #数据库配置mysql
  datasource:
    url: jdbc:mysql://172.16.31.91/ai-studio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
##自定义文件地址配置##
file:
  address: /user/hadoop
##hadoop文件系统参数定义##
hadoop:
  mapProps:
    defaultFs: fs.defaultFS
    host: hdfs://172.16.31.91:9000
    defaultImagePath: /user/hadoop/default/image/001.jpg



