server:
  port: 8082


spring:
  application:
      name: oauth
  cloud:
      client:
        ipAddress: localhost
  redis:
    host: 182.92.82.3
    database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/stretch/eureka/
  instance:
    hostname: oauth2
