server:
  port: 8052


spring:
  application:
      name: oauth
  cloud:
      client:
        ipAddress: localhost
  redis:
    host: 47.105.127.125
    database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
  instance:
    hostname: oauth2
