server:
  port: 8082


spring:
  application:
      name: oauth
  cloud:
      client:
        ipAddress: localhost
  redis:
    host: 127.0.0.1
    database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
  instance:
    hostname: oauth2
