server:
  port: 8052


spring:
  application:
      name: oauth
  cloud:
      client:
        ipAddress: localhost
  redis:
      host: 47.105.127.125
      database: 0
      port: 6479
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms
      timeout: 2000ms
      password: Deepthought2018

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
  instance:
    hostname: oauth2
