server:
  port: 8082


spring:
  redis:
    host: 172.16.31.233
    database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/stretch/eureka/
  instance:
    hostname: oauth2
