eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.81.16:8080/stretch/eureka/
server:
  port: 8084
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon

spring:
  application:
    name: zuul
  cloud:
      client:
        ipAddress: localhost
security:
  oauth2:
    resource:
      jwt:
        key-value: \
                   -----BEGIN PUBLIC KEY-----\
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp53cfat+TAgYgak9sFiQkzpds8O3BhHnlvJJSbgRuvPTI8BAKbkrr+nUsu5M/Kz4JTfd1xvbpVe9wpD9hprtmRcWg9PIZYlN8tbg+9uUE3Gcl58FsrefJAab0BU5VmzLY6KCDd/4lZAuZLCwKjcs05qrarJpDenZsoqiVcPYcAydVXQGQuJJ/NdEbxj3L07AkhMMn1kt+/OzKWpo3ArYt3CkGmzz7Aty0Hem5XQJa1VKFccK2AETnfvtHkcuCF23jfiZl2U1QQu+r4nHf3ES87O72eMICjXyH4+427hZsVHaAgD9pSoa5iFvGjSPPWCJxkPdcPi2CWXWySnVpdG0EQIDAQAB\
                   -----END PUBLIC KEY-----
    sso:
      login-path: /login
    client:
      access-token-uri: http://172.16.81.16:8089/uaa/oauth/token
      user-authorization-uri: http://localhost:8089/uaa/oauth/authorize
      client-id: client
      client-secret: secret












