eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/stretch/eureka/
server:
  port: 8084
zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: account
    uaa:
      path: /cross-brain/**
      sensitiveHeaders:
      serviceId: dataset
    api-a:
      path: /api-a/**
      serviceId: ribbon

spring:
  application:
    name: zuul
  cloud:
      client:
        ipAddress: localhost
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
#security:
#  oauth2:
#    client:
#      access-token-uri: http://oauth2/uaa/oauth/token
#      user-authorization-uri: http://oauth2/uaa/oauth/authorize
#      client-id: webapp
#    resource:
#      user-info-uri: http://localhost:8086/uaa/user
#      prefer-token-info: false












