server:
  port: 8051
  servlet:
    context-path: /stretch
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/stretch/eureka
    instance:
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  cloud:
    client:
      ipAddress: localhost