server:
  port: 8087
  servlet:
    context-path: /stretch
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
  instance:
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  cloud:
    client:
      ipAddress: localhost
  application:
    name: account