server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/stretch/eureka/
logging:
  level:
    com.yasaka.stock.feign.MFeignClient: debug
spring:
  application:
    name: feign
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
