server:
  port: 8089
  servlet:
    context-path: /uaa
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.81.16:8080/stretch/eureka/
  instance:
    hostname: 172.16.81.16
spring:
  cloud:
    client:
      ipAddress: 172.16.81.16
  application:
    name: oauth2



