server:
  port: 8083
  servlet:
      context-path: /stretch  #如果加了 路由url那里也要加，隐藏不掉

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #自定义
spring:
  cloud:
    client:
      ipAddress: localhost
  application:
    name: ribbon